#!/usr/bin/env bash
# Double the number of webservers
apt-get -y update;
apt-get -y install nginx;
ufw allow "Nginx HTTP";
echo "Hello World!" | sudo tee /var/www/html/index.html;
sed -i "/listen 80/a\\\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
newlines="\\\terror_page 404 /404.html\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "/listen 80/a${newlines}" /etc/nginx/sites-available/default
sed -i "/listen 80/a\\\t\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default service nginx restart
