#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update;
apt-get -y install haproxy;
echo "
frontend www
	bind *:80
	default_backend web-backend

backend web-backend
	balance roundrobin
	server web1 54.146.93.232:80 check
	server web2 100.26.17.110:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
