#!/usr/bin/env bash
# Install and setup HAproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/HAproxy-1.8
apt-get -y update
apt-get install -y HAproxy=1.8.\*

echo "ENABLED=1" > /etc/default/HAproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 119412-web-01 54.146.93.232:80 check
   server 119412-web-02 100.26.17.110:80 check
" >> /etc/HAproxy/HAproxy.cfg

service HAproxy start
